### ISSUE TITLE
Command line arguments to vscode-portable.exe doesn't get to VS Code

### ISSUE THREAD

**Issue by mfedatto** [portapps/vscode-portable#1]
### Behaviour

Command line arguments given to vscode-portable.exe aren't reaching VS Code binary.

#### Steps to reproduce this issue

1. `code .` command opens VS Code with working directory as folder, but `vscode-portable.exe .` only opens VS Code Portable as it was when closed
2. `code --version` shows VS Code version, but `vscode-portable.exe .` only opens VS Code Portable as it was when closed
3.`code --list-extensions` shows a list of installed extensions, but `vscode-portable.exe .` only opens VS Code Portable as it was when closed

#### Expected behaviour

I assumed vscode-portable.exe should behavior like code, but on portable context.

#### Actual behaviour

It seems no vscode-portable.exe arguments are passed when lounching VS Code

### Configuration

**App release / arch (ex. 1.0.0-2 win64)** : 

**Operating system (ex. Windows 10 Pro 64 bits)** : Windows 10 Pro 64 bits

**Winver screenshot** :

![winver](https://user-images.githubusercontent.com/5623739/45509193-3bf48900-b76d-11e8-85f1-a40657e61df6.png)

### Screenshots

> If applicable, add screenshots to help explain your problem.

### Logs

Join the log file `vscode-portable.log` to this issue.

**Comment by crazy-max** [comment]
@mfedatto Ok gotcha, we have to use `app\bin\code` and not `app\Code.exe` if args are passed. Will be solved in the next release.

**Comment by crazy-max** [comment]
It should be ok now (see latest release)

**Comment by mfedatto** [comment]
Working fine now!
