### ISSUE TITLE
ms-python.python extension doesn't work

### ISSUE THREAD

**Issue by FlotterCodername** [portapps/vscode-portable#21]
### Behaviour
Can't properly set up Microsoft Python extension, even if manually pointing to the correct folder on my portable drive.

### Configuration
**App release / arch** : 1.49.3-39
**Operating system** : Windows 10 Pro x64, multiple versions including 1703 and 2004

### Logs
[VSCode Python Extension](https://pastebin.com/WQ7JizNF)
VS IntelliCode below:
```
Language server is set to Microsoft.
Acquiring model 'intellisense-members-lstm' for python
Querying IntelliCode service for available models.
vs-intellicode-python was passed a model: {}.
Cached model is up to date.
Error while activating Python: {}
```

**Comment by crazy-max** [comment]
@FroyoXSG Looks like this extension requires a valid Python installation which is not (ant will not be) provided by this portapp. I suggest to open an issue on the official repo about this: https://github.com/microsoft/vscode/issues. Btw does it work with the standard vscode setup?

**Comment by FlotterCodername** [comment]
@crazy-max Well, it doesn't even work when pointing Code to a Python installation on the local computer.
I have since switched to the Microsoft-provided method for using Code portably.* The same issue persists. So you can only use this extension with 'installed' copies of Code, as I see it.

*(this means downloading and extracting the vscode zip and creating a folder "data" in it)

**Comment by FlotterCodername** [comment]
No longer happening
