### ISSUE TITLE
Update Path

### ISSUE THREAD

**Issue by f0ru0l0rd** [portapps/vscode-portable#24]
### Behaviour
VS Code recently had very important updates.
There appears to be no upgrade path, or at least no information on an upgrade path or instructions in portapp.

_I realize that portapp is just a go wrapper for the application, and theoretically it doesn't matter what app it is given, nor the version and is likely downloaded by the client from a current stable build branch for the main app, but it would be good to have the information on how to update and to validate if this is correct._

### Version
VS Code 1.51.1

### Result
Clicking the Download Update button downloads a zip file with no instructions on update.

**App release / arch (ex. 1.0.0-2 win64)** :

Win10 64Bit

**Comment by crazy-max** [comment]
Instructions are on the website: https://portapps.io/app/vscode-portable/
